# Generated by Django 2.1.5 on 2020-06-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0003_createblog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createblog',
            name='datetime',
        ),
    ]
