# Generated by Django 2.1.5 on 2020-06-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0004_remove_createblog_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createblog',
            old_name='Name',
            new_name='Author_Name',
        ),
        migrations.AddField(
            model_name='createblog',
            name='Date_of_blog',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
