# Generated by Django 2.1.5 on 2020-06-06 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0005_auto_20200606_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createblog',
            name='Date_of_blog',
        ),
    ]
