# Generated by Django 2.1.5 on 2020-06-06 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0007_createblog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='content_blog',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
