# Generated by Django 2.1.5 on 2020-06-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0008_createblog_content_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='picture',
            field=models.ImageField(default='download.jpeg', upload_to=''),
        ),
    ]
