# Generated by Django 2.1.5 on 2020-06-07 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0009_createblog_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='places',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createblog',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
