# Generated by Django 2.1.5 on 2020-06-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0010_auto_20200606_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createblog',
            name='content_blog',
        ),
        migrations.RemoveField(
            model_name='createblog',
            name='picture',
        ),
    ]
