# Generated by Django 2.1.5 on 2020-06-08 03:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0011_auto_20200607_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='content_blog',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createblog',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
