# Generated by Django 2.1.5 on 2020-06-08 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0012_auto_20200607_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='ReEnterPassword',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
